providers = ["php", "node", "staticfile"]

[phases.build]
cmds = [
    "npm ci",
    "npm run build",
    "php artisan migrate --force",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:clear",
    "php artisan view:cache"
]

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://pura-vida-rides-production.up.railway.app"
ASSET_URL = "https://pura-vida-rides-production.up.railway.app"
NIXPACKS_PHP_ROOT_DIR = "/app/public"
APP_KEY = "base64:q2Hze5dfTzap+gT74GvoVypFt8MQD+UAxUd3CHq0bDA="
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"
SESSION_DRIVER = "file"
CACHE_STORE = "file"
QUEUE_CONNECTION = "sync"
