[phases.setup]
nixPkgs = ["...", "php81", "php81Packages.composer", "nginx"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[phases.build]
cmds = [
    "npm ci",
    "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"